<WelcomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

<LoginScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

<RegisterScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10
